---
title: "Data wrangling"
output:
  word_document: default
  html_document:
    df_print: paged
  pdf_document: default
---

```{r, include=FALSE}
knitr::opts_chunk$set(include=FALSE)

library(tidyverse)

# using Google sheets API
library(googlesheets4)

# overview
library(skimr)

# scrape stories
library(rvest)

# for dates
library(lubridate)
```

```{r, eval = FALSE, include=FALSE}
# Get data from Google Sheets
input_form <- googlesheets4::read_sheet("https://docs.google.com/spreadsheets/d/1E49jzOxKPe1UmXFzkjUItEDj_TXHLiC4XUt3kVn7kVI/edit#gid=1315458627")

write_csv(input_form, "data/input_form.csv")

# this is a copy in Liza's drive due to dates being formatted in more than one way in original doc (just birth year)
author_index <- googlesheets4::read_sheet("https://docs.google.com/spreadsheets/d/1degAmrldvjhnZm6l8nki4vT2LZqz13-TDfwjAWR_9GY/edit#gid=0")

write_csv(author_index, "data/author_index.csv")

# this is a copy in Liza's drive due to dates being formatted in more than one way in original doc
story_index <- googlesheets4::read_sheet("https://docs.google.com/spreadsheets/d/1gNqxEli3dAGXtxwHsc1RpnrknFJLNWMsrD5yucrt08o/edit#gid=0") 

write_csv(story_index, "data/story_index.csv")
```

# Raw
```{r, include=FALSE}
input_form <- read_csv("data/input_form.csv")
author_index <- read_csv("data/author_index.csv")
story_index <- read_csv("data/story_index.csv")
```

```{r, include=FALSE}
input_form_clean <- input_form %>% 
  janitor::clean_names() %>% 
  select(-timestamp, -annotator_number_1_code, -annotator_number_2_code)

author_index_clean <- author_index %>% 
  janitor::clean_names()

# some incomplete publishing info
story_index_clean <- story_index %>% 
  janitor::clean_names() %>% 
  select(story_code, story_title, story_url, date_of_first_publication_yyyy_mm_dd, format_of_first_publication_journal_or_book, name_of_journal_or_title_of_book) %>% 
  rename(story_name = "story_title")

detective_data <- input_form_clean %>% 
  left_join(author_index_clean, by = "author_code") %>% 
  left_join(story_index_clean, by = c("story_code", "story_name")) %>% 
  select(-upload_plain_text_file_here_named_as_story_code_txt)

```

# Read text
```{r, eval = TRUE}

read_story <- function(x) {
  text <- read_html(x) %>% 
  html_nodes("p") %>% 
  html_text() %>% 
  glue::glue_collapse(sep = " ")
  
  return(text)
}

story_text_list <- detective_data %>% 
  filter(!str_detect(story_url, ".txt")) %>% 
  filter(!str_detect(story_url, " ")) %>% 
  filter(!str_detect(story_url, "#")) %>% 
  select(story_url, story_code, what_is_the_reveal_border_sentence)

# Takes a while to run
# story_text <- map_dfr(.x = c(url = story_text_list$story_url), .f = read_story)

# saveRDS(story_text, "story_text.rds")
```


```{r}
story_text <- readRDS("story_text.rds")

story_text_clean <- story_text %>% 
  pivot_longer(everything(), values_to = "text") %>% 
  select(-name) %>% 
  mutate(story_code = story_text_list$story_code, 
         what_is_the_reveal_border_sentence = story_text_list$what_is_the_reveal_border_sentence) %>% 
  mutate(text_length = str_count(text)+1)

# head(story_text_clean)

only_reveals <- story_text_clean %>% 
  select(what_is_the_reveal_border_sentence) %>% 
  filter(!is.na(what_is_the_reveal_border_sentence))

my_sep <- glue::glue_collapse(only_reveals$what_is_the_reveal_border_sentence, sep = "|")

split <- story_text_clean %>% 
  mutate(text_words = str_count(text)+1) %>% 
  rowwise() %>% 
  separate(text, into = c("before_reveal", "after_reveal", "uhoh"), sep = my_sep) %>% 
  mutate(after_reveal = if_else(is.na(uhoh), after_reveal, uhoh)) %>% 
  select(-uhoh) %>% 
  mutate(before_reveal_words = str_count(before_reveal)+1,
         after_reveal_words = str_count(after_reveal)+1)


split %>% 
  ggplot(aes(x = text_words, y = after_reveal_words)) +
  geom_point()

word_counts_text <- split %>% 
  select(story_code, contains("words"))

```

Variables with all missing have been removed from the data

```{r}
detective_data_1 <- detective_data %>% 
  left_join(word_counts_text, by = "story_code") %>% 
  mutate(title_words = str_count(story_name)+1) %>% 
  mutate(before_reveal_words = if_else(is.na(after_reveal_words), NaN, before_reveal_words)) %>% 
  select(-where(function(x) all(is.na(x)))) %>% 
  mutate(date_of_first_publication_yyyy_mm_dd = as_date(date_of_first_publication_yyyy_mm_dd),
         year_of_birth = as_date(year_of_birth),
         date_of_death_yyyy_mm_dd = as_date(date_of_death_yyyy_mm_dd)) %>% 
  mutate(unique = duplicated(story_code)) %>% 
  mutate(year_published = parse_number(format(date_of_first_publication_yyyy_mm_dd, format="%Y")))


detective_data_1 %>% 
  select(story_code, unique) %>% 
  View()
```

# Create a data dictionary

```{r, include = TRUE}
print_levels <- function(x){
  new_x = x[!is.na(x)]
  paste0("\"", glue::glue_collapse(unique(new_x), sep = "\", \""), "\"")
} 

print_levels(detective_data_1$detective_number_1_gender)

my_skim <- skim(detective_data_1)


get_levels_small_c <- tibble(variable_name = names(select(detective_data_1, my_skim$skim_variable[which(my_skim$skim_type == "character" & my_skim$character.n_unique < 20)])), notes1 = sapply(select(detective_data_1, my_skim$skim_variable[which(my_skim$skim_type == "character" & my_skim$character.n_unique < 20)]), print_levels))

get_levels_large_c <- tibble(variable_name = names(select(detective_data_1, my_skim$skim_variable[which(my_skim$skim_type == "character" & my_skim$character.n_unique >= 20)])), notes1 = "Too many long/unique levels to show here. See the data collection instructions for more information.")


mins <- map_dfc(select(detective_data_1, my_skim$skim_variable[which(my_skim$skim_type == "numeric")]), min, na.rm = TRUE) %>% 
  pivot_longer(everything())
means <- map_dfc(select(detective_data_1, my_skim$skim_variable[which(my_skim$skim_type == "numeric")]), mean, na.rm = TRUE) %>% 
  pivot_longer(everything())
medians <- map_dfc(select(detective_data_1, my_skim$skim_variable[which(my_skim$skim_type == "numeric")]), median, na.rm = TRUE) %>% 
  pivot_longer(everything())
maxs <- map_dfc(select(detective_data_1, my_skim$skim_variable[which(my_skim$skim_type == "numeric")]), max, na.rm = TRUE) %>% 
  pivot_longer(everything())

get_summary_n <- bind_cols(mins, means, medians, maxs) %>% 
  rename(variable_name = 1) %>% 
  select(variable_name, contains("value")) %>% 
  mutate(notes1 =
           str_c("Min: ", value...2, ", Mean: ", round(value...4,1), ", Median: ", value...6, ", Max: ", value...8)) %>% 
  select(variable_name, notes1)

get_summary_date <- tibble(variable_name = names(select(detective_data_1, my_skim$skim_variable[which(my_skim$skim_type == "Date")])), notes1 = "Date variable")

all_descriptors <- bind_rows(
  get_levels_small_c,
  get_levels_large_c,
  get_summary_date,
  get_summary_n
) 


data_dic <- tibble(variable_name = my_skim$skim_variable,
                   data_type = my_skim$skim_type,
                   n_missing = my_skim$n_missing) %>% 
  left_join(all_descriptors, by = "variable_name") %>% 
  relocate(n_missing, .after = 4)

#table(my_skim$skim_type)
#table(my_skim$character.n_unique)

flextable::flextable(data_dic)

```

